apiVersion: v1
kind: PersistentVolume
metadata:
    name: miniapp-cassandra-persistent-volume
spec:
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/data/miniapp/cassandra"