apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniapp-cassandra-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: miniapp-cassandra-persistent-volume
  storageClassName: ""