apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: miniapp
      app: miniapp
  template:
    metadata:
      labels:
        component: miniapp
        app: miniapp
    spec:
      containers:
        - name: miniapp
          image: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp:76589aca50766fabcbbe08eb32e7a97713d9e6bd
          #image: 192.168.1.3:5000/miniapp-impl:0.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
            - name: JAVA_OPTS
              value: "-Dconfig.resource=application-k8s.conf"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniapp 
                  key: pgpassword
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 60
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
      imagePullSecrets:
        - name: awsecr-cred