apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/miniapp

images:
- name: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp
  newTag: f168c10b4bd164d321e2a3d49bd1145391a66af1

patchesJson6902:
- path: patch-miniapp.yaml
  target:
    group: apps
    kind: Deployment
    name: miniapp-deployment
    version: v1
