apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/miniapp

images:
- name: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp
  newTag: a38fbf4aa2e742ab09819d0b5d9fdc90747bfa4a

patchesJson6902:
- path: patch-miniapp.yaml
  target:
    group: apps
    kind: Deployment
    name: miniapp-deployment
    version: v1
