apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/miniapp

images:
- name: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp
  newTag: 56838eb8a8f9d4ed0bc153e5f94ae3448456e4c5

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: miniapp-deployment
  path: patch-miniapp.yaml