apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/miniapp

images:
- name: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp
  newTag: 4682cbc9ea37e402bce4eef8ae458094d17d8ce5

patchesJson6902:
- path: patch-miniapp.yaml
  target:
    group: apps
    kind: Deployment
    name: miniapp-deployment
    version: v1
