apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/miniapp

images:
- name: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp
  newTag: 206e24cb015b85436756fb56f66e323b7b6208d8

patchesJson6902:
- path: patch-miniapp.yaml
  target:
    group: apps
    kind: Deployment
    name: miniapp-deployment
    version: v1
