apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/miniapp

images:
- name: 510158725010.dkr.ecr.us-east-1.amazonaws.com/goxhere/miniapp
  newTag: 9175ed29c2be7d7a2b9c1e6e7d2923df33bf9513

patchesJson6902:
- path: patch-miniapp.yaml
  target:
    group: apps
    kind: Deployment
    name: miniapp-deployment
    version: v1
