apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./miniapp-postgres-deployment.yaml
- ./miniapp-postgres-nodeport-service.yaml
- ./miniapp-postgres-persistent-volume-claim.yaml
- ./miniapp-postgres-persistent-volume.yaml