apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniapp-postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: miniapp-postgres-persistent-volume
  storageClassName: ""