apiVersion: v1
kind: PersistentVolume
metadata:
    name: miniapp-postgres-persistent-volume
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/data/miniapp/postgres"